# TODO: add this to custom css when firefox supports it
#form:has(> label[for="filter-tiles"]) {
#  display: none!important;
#}
pageInfo:
  title: starrnix
  description: get nixxed
  navLinks:
    - title: GitHub
      path: https://github.com/Lissy93/dashy
    - title: Documentation
      path: https://dashy.to/docs
appConfig:
  theme: basic
  layout: auto
  iconSize: medium
  language: en
  customCss: footer,header{display:none!important;}
  customColors:
    basic:
      primary: '#FFFFFF'
      background: '#000000'
      background-darker: '#000000'
sections:
  - name: Services
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: Jellyfin
        icon: favicon
        url: http://nixtop:8096/
        target: newtab
        statusCheck: true
        statusCheckAllowInsecure: true
  - name: Websites
    displayData:
      sortBy: most-used
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: Youtube
        icon: favicon
        url: https://youtube.com
      - title: At&t Router
        icon: favicon
        url: http://192.168.1.254
      - title: Anilist
        icon: favicon
        url: https://anilist.co
      - title: Anichart
        icon: favicon
        url: https://anichart.net/airing
