[imhex]
src.github = "WerWolv/imhex"
fetch.github = "WerWolv/imhex"
git.fetchSubmodules = true

[imhex-patterns]
src.github = "WerWolv/ImHex-Patterns"
fetch.github = "WerWolv/ImHex-Patterns"

[gh-poi]
src.github = "seachicken/gh-poi"
fetch.github = "seachicken/gh-poi"
passthru = {vendorSha256 = "sha256-D/YZLwwGJWCekq9mpfCECzJyJ/xSlg7fC6leJh+e8i0="}

[vscord]
src.vsmarketplace = "LeonardSSH.vscord"
fetch.vsmarketplace = "LeonardSSH.vscord"
